Skill
		////Uzumaki///
	Rasengan
		name="Rasengan"
		icon='skills.dmi'
		icon_state="Rasengan"
		chakracost=150
		cooldown=60
		maxcooldown=60
		sindex="Rasengan"
		procedure="Rasengan"

	Oodama_Rasengan
		name="Oodama_Rasengan"
		icon='skills.dmi'
		icon_state="Oodama_Rasengan"
		chakracost=180
		cooldown=80
		maxcooldown=80
		sindex="Oodama_Rasengan"
		procedure="Rasengan"